### ISSUE TITLE
Teleporting to protected beacons is possible

### ISSUE THREAD

**Issue by Montandalar** [pandorabox-io/telemosaic#14]
It's possible to target any beacon, even protected ones in areas you have no access to, by assigning the destination with digilines. The privs of the area owner of the source and the destination should be compared to make sure they are compatible, and refuse if the player wouldn't be able to bypass the protection e.g. unless they have `protection_bypass`.

**Comment by OgelGames** [comment]
Yes, this is correct behavior. The same is possible without digilines, you can make a key for any beacon, protected or not.

And no, I don't think that behavior should be changed, it's one of the main advantages of using telemosaics for public places.

**Comment by Montandalar** [comment]
What is the purpose of the protected beacon if not to block travel to the unauthorised? Just to prevent removing it in case the area isn't protected with something like areas or protector mods?

**Comment by Montandalar** [comment]
Even if the protected beacon isn't changed, I'd like a private beacon that can only be used be authorised users, as a third option.

**Comment by Maverick2797** [comment]
If the protection logic was moved from the linking process to the teleport process then you'd still be able to set the destination as per normal, except you can now block access to private areas by having the destination as a protected telemosaic. There would be no need for a third type of telemosaic, instead relying on area/protector mods to grant teleport access.

**Comment by S-S-X** [comment]
Protected beacon could be easily made private without adding new beacons in a way that it would just be additional configurable feature for current protected beacons.
Without adding any additional user interfaces this could be done either through crafting, through digiline message or both.

That would also allow server wide configuration to enable/disable fully private beacons any time back and forth.

Also I think that @Maverick2797's suggestion should be implemented, it isn't exactly strictly necessary to achieve private beacons without new nodes but would offer restrictions for old sources that are linking to protected targets:

> protection logic was moved from the linking process to the teleport process

**Comment by S-S-X** [comment]
Frame challenge @OgelGames:

> main advantages of using telemosaics for public places.

Public places should not use protected beacons but instead public places should use normal beacons. I think it would be good to consider changing protection logic.

**Comment by OgelGames** [comment]
> What is the purpose of the protected beacon if not to block travel to the unauthorised?

Protected beacons cannot be used by other players; their destination is protected.

> protection logic was moved from the linking process to the teleport process

That's how it works already, but there's only a check for the source beacon, not the destination.

> Public places should not use protected beacons but instead public places should use normal beacons. I think it would be good to consider changing protection logic.

Yeah, I think it makes sense to change it. Also, there's a use case the change would make possible: a digiline-powered multi-destination beacon with some public and some protected destinations.

**Comment by Maverick2797** [comment]
> > What is the purpose of the protected beacon if not to block travel to the unauthorised?
> 
> Protected beacons cannot be used by other players; their destination is protected.

That does nothing to prevent other people with a telemosaic (protected or not) locking onto your landing pad in a private area to gain access. The protection check currently only stops people teleporting _from_ a protected beacon, not _to_ one.

> Yeah, I think it makes sense to change it. Also, there's a use case the change would make possible: a digiline-powered multi-destination beacon with some public and some protected destinations.

That's what originally perked my interest to the telemosaic. I had a teleport-pad feed tape powered entirely by mesecon pistons and a node detector on another server, but full digiline programming would be much easier to maintain.

**Comment by OgelGames** [comment]
Done. Now protected beacons protect the source and the destination.
