### ISSUE TITLE
translation support

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/telemosaic#18]
See https://content.minetest.net/threads/7531/

```
Frankly, I bumped into it through worldgate, but telemosaic is wonderful in itself. A very different feel from anything like travelnet; Telemosaic has an esthetic of its own, a bit eerie, and the mechanic is interesting.

Please please make it translatable. I badly need everything translated for a server with players with mild aphasia, and the innards of the mod are a bit too hard for me to untangle and steal-translate properly.
```

**Comment by wsor4035** [comment]
this is a test, please ignore this (probably) spam

**Comment by Montandalar** [comment]
I'm working on i18n and a German locale for telemosaic.. I posted a modding discussion question and answer to the forums about my problems along the way, though GitHub seems to kill the comment if I give a direct link...

1-2 days and it should be done.

**Comment by wsor4035** [comment]
this is the forum link for above: https://forum.minetest.net/viewtopic.php?p=433140

lets see if github doesnt like this
