### ISSUE TITLE
Move to "mt-mods"

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/telemosaic#7]

**Comment by S-S-X** [comment]
Note that github knows how to redirect git url's after repository has moved and therefore no big preparations are needed as after move repo should work with both old and new location for git commands (clone, pull, push, etc).
However, no idea how long this redirection will hold but my experience is several weeks at least.

**Comment by BuckarooBanzay** [comment]
>  However, no idea how long this redirection will hold but my experience is several weeks at least.

I have some old links from 2 years ago, they are still redirecting to the new location :smile:

**Comment by BuckarooBanzay** [comment]
done :smile:
